[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
