[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
jsonrpc = { path = "../jsonrpc" }
async-trait.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
